apiVersion: v1
kind: Service
metadata:
  name: rollout-analysis-step
  labels:
    app: rollout-analysis-step
spec:
  selector:
    app: rollout-analysis-step
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-analysis-step-preview
  labels:
    app: rollout-analysis-step
spec:
  selector:
    app: rollout-analysis-step
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
