# Default values for helm-rollout.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: "kirbah/blue-green"
  # name: "argoproj/rollouts-demo"
  tag: "green"

probes:
  # ready: "/live"
  # live:  "/health"
  port: 8080
  ready: "/health"
  live:  "/live"
